### ISSUE TITLE
Screensaver stops working

### ISSUE THREAD

**Issue by mumpitzstuff** [aabytt/custom-screensaver-aerial#14]
The screensaver works most of the time but sometimes a video can not be loaded somehow which results in a black screen forever.
![20240612_130145](https://github.com/aabytt/custom-screensaver-aerial/assets/1314762/c7dfb6da-410c-470a-a601-45dd77d917c0)
![20240611_215707](https://github.com/aabytt/custom-screensaver-aerial/assets/1314762/0a9d9e92-b475-4802-8376-034d6a07c02a)

Is there any way to detect such a problem and to switch to another video in such a case?

**Comment by aabytt** [comment]
@mumpitzstuff for some reason playback gets `stopped` status. this was not expected to happen. anyway, I will add a handler for this status and it will try next video after some timeout.

**Comment by aabytt** [comment]
@mumpitzstuff please try the new released version

**Comment by mumpitzstuff** [comment]
Looks good so far. The playback state changes from playing to stopped if any new video is loaded and stay within this state until the new video is buffered (which can take 3-4s on bigger videos). I do not know if this is just the case on my tv... The new version decreases the stalled timeout now on playback state stopped which should do the job in my opinion.

**Comment by mumpitzstuff** [comment]
Hmm was a bit to early. 
![20240612_161208](https://github.com/aabytt/custom-screensaver-aerial/assets/1314762/c125933a-4b5d-4433-88cc-fa02669ba3bb)
The whole thing is frozen. Stalled timeout is not decreased anymore... nothing. But i can just press the back button on my remote and start the test run again.

**Comment by aabytt** [comment]
Have you made a full reboot after updating the app?

**Comment by mumpitzstuff** [comment]
Can not remember me. But anyway your change make sense to me and the reason for the crash might sit in front of my tv. I will try to run it for some time and to analyze the syslog in parallel.
