### ISSUE TITLE
Screensaver not working

### ISSUE THREAD

**Issue by Philipou** [aabytt/custom-screensaver-aerial#17]
Hey, so I downloaded the screensaver using the manual method because the certificate keys have a problem right now and I needed to use ssh (I used [this](https://github.com/webosbrew/webos-homebrew-channel/issues/179#issuecomment-2106675279)) and the screensaver is black a few seconds then shows a screenshot of the app behind as if It was "transparent". I tried every quality options and different languages but nothing is working...

**Comment by aabytt** [comment]
What's your TV model?

**Comment by Philipou** [comment]
Hey, sorry for not providing any info !

My TV is a 43UM7050PLF

Web os version is 4.10.0-12 (goldilocks2-grampians)

Got 400mb free out of 600

Here is a picture of what's happening:
![20240709_131303.jpg](https://github.com/aabytt/custom-screensaver-aerial/assets/71514309/5892ada9-7cfb-4b66-8987-e121289eafc6)

Hope that helps you fix the problem :)

**Comment by aabytt** [comment]
> My TV is a 43UM7050PLF

This is webOS 4.x TV
Screensaver works for webOS 5+

**Comment by Philipou** [comment]
Oh ok will there be web os 4 support in the future ?

**Comment by aabytt** [comment]
> Oh ok will there be web os 4 support in the future ?

WebOS 4 is missing some elements making video playback possible within native screensaver app type. 
Will need to check some hacks and workarounds.
No ETA, sorry
