### ISSUE TITLE
The screensaver images not show

### ISSUE THREAD

**Issue by xakepa** [aabytt/custom-screensaver-aerial#20]
The screensaver images not show. Instead transparent image show and the captions of the image but the image is missing.
tested on LG OLED55B8PLA Sometimes just black screen.
Firmware version 5.50.15
WebOS version: 4.4.0

![viber_изображение_2024-08-04_12-48-53-251](https://github.com/user-attachments/assets/cb7f4631-7db6-4bb1-b180-cce5398d002f)

**Comment by xakepa** [comment]
![viber_изображение_2024-08-04_12-48-53-251](https://github.com/user-attachments/assets/cb7f4631-7db6-4bb1-b180-cce5398d002f)

**Comment by xakepa** [comment]
London Evening
![Uploading viber_изображение_2024-08-04_12-52-31-632.jpg…]()

**Comment by xakepa** [comment]
![viber_изображение_2024-08-04_12-52-31-632](https://github.com/user-attachments/assets/26b27533-d711-4960-bcad-a30de1d32596)

**Comment by xakepa** [comment]
This suppose to be London Evening (don't mind the reflection)

![viber_изображение_2024-08-04_12-56-23-263](https://github.com/user-attachments/assets/d659e9f5-3e3b-43cb-a516-9ab5b8435ba4)

**Comment by aabytt** [comment]
webOS 5+ required
