### ISSUE TITLE
Aerial Screensaver (Add Images)

### ISSUE THREAD

**Issue by Pablo-Martinetz** [aabytt/custom-screensaver-aerial#24]
Wehre can i add my custom images for this screen safer

**Comment by aabytt** [comment]
There is no such an option but you can modify `videos.json` file on your TV to add some own sources (videos)

**Comment by Pablo-Martinetz** [comment]
And where is that file stored?

**Comment by aabytt** [comment]
> And where is that file stored?

You can find it in the installed app directory
`/media/developer/apps/usr/palm/applications/org.aabytt.webos.custom-screensaver-aerial/assets/`
