### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by mato200** [aabytt/custom-screensaver-aerial#25]
Just rooted my LG C3 TV, but the screensavers arent working. I click on Test and its just fireworks like before.
I actually want to replace those bright colorful artsy screensavers that appear after some time but they only appear when i am (not) using my PC connected via HDMI. I wish i could use other pictures or at least have firefowrks screensaver instead of artsy colors while using HDMI input. I also tried older app this is based on. and that one is also not working.

**Comment by x134h34kr** [comment]
also have the same issue. any recommendation?

**Comment by aabytt** [comment]
you need to apply temporarily before testing otherwise original screensaver is not being replaced by custom
